title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://arihu1008.github.io/docs-jekyll

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

collections:
  how-to:
    # permalink: "/:collection/:name"
    output: true
# defaults:
#   -
#   scope: {path: "*"}
#   values: {layout: default}
just-the-docs:
  collections:
    how-to:
      name: How To Guides
      nav_fold: true
